{
 "title": "Monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "TCP Connections in use",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "netdata_ipv4_sockstat_tcp_sockets_sockets_average{chart=\"ipv4.sockstat_tcp_sockets\", dimension=\"inuse\", family=\"tcp\", instance=\"10.0.2.17:19999\", job=\"netdata-scrape\"}",
     "legendFormat": "tcp connections chart"
    }
   ]
  },
  {
   "title": "TCP Connections orphan",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "netdata_ipv4_sockstat_tcp_sockets_sockets_average{chart=\"ipv4.sockstat_tcp_sockets\", dimension=\"orphan\", family=\"tcp\", instance=\"10.0.2.17:19999\", job=\"netdata-scrape\"}",
     "legendFormat": "tcp connections chart"
    }
   ]
  },
  {
   "title": "Total Open Sockets",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(netdata_apps_sockets_open_sockets_average)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Traffic (enp0s8)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "netdata_net_net_kilobits_persec_average{chart=\"net.veth1c1c50b\", dimension=\"received\", family=\"veth1c1c50b\", instance=\"10.0.2.17:19999\", job=\"netdata-scrape\"}",
     "legendFormat": "traffic received chart"
    },
    {
     "expr": "netdata_net_net_kilobits_persec_average{chart=\"net.veth1c1c50b\", dimension=\"sent\", family=\"veth1c1c50b\", instance=\"10.0.2.17:19999\", job=\"netdata-scrape\"}",
     "legendFormat": "traffic sent chart"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "netdata_cpu_cpu_percentage_average{chart=\"cpu.cpu0\", dimension=\"user\", family=\"utilization\", instance=\"10.0.2.17:19999\", job=\"netdata-scrape\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage Flow",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "netdata_cpu_cpu_percentage_average{chart=\"cpu.cpu0\", dimension=\"user\", family=\"utilization\", instance=\"10.0.2.17:19999\", job=\"netdata-scrape\"}",
     "legendFormat": "cpu chart"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "netdata_system_ram_MiB_average{chart=\"system.ram\", dimension=\"used\", family=\"ram\", instance=\"10.0.2.17:19999\", job=\"netdata-scrape\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Free",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "netdata_system_ram_MiB_average{chart=\"system.ram\", dimension=\"free\", family=\"ram\", instance=\"10.0.2.17:19999\", job=\"netdata-scrape\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "netdata_system_uptime_seconds_average",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}