{
 "title": "DoS Monitoring",
 "time": { "from": "2025-09-04T10:47:42.589Z", "to": "2025-09-04T10:50:42.259Z" },
 "panels": [
  { "title": "TCP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "TCP ACTIVE CONNETIONS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "netdata_ipv4_sockstat_tcp_sockets_sockets_average{chart=\"ipv4.sockstat_tcp_sockets\", dimension=\"inuse\", family=\"tcp\", instance=\"10.0.2.17:19999\", job=\"netdata\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TCP ORPHAN CONNECTIONS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "netdata_ipv4_sockstat_tcp_sockets_sockets_average{chart=\"ipv4.sockstat_tcp_sockets\", dimension=\"orphan\", family=\"tcp\", instance=\"10.0.2.17:19999\", job=\"netdata\"}\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "HEALTH", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - netdata_system_cpu_percentage_average{dimension=\"idle\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM BUSY",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "netdata_system_ram_MiB_average{chart=\"system.ram\", dimension=\"used\", family=\"ram\", instance=\"10.0.2.17:19999\", job=\"netdata\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NETWORK TRAFFIC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "netdata_net_net_kilobits_persec_average{chart=\"net.ens3\",dimension=\"received\",family=\"ens3\",interface_type=\"real\",device=\"ens3\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM FREE",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "netdata_system_ram_MiB_average{chart=\"system.ram\", dimension=\"free\", family=\"ram\", instance=\"10.0.2.17:19999\", job=\"netdata\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UPTIME",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "netdata_system_uptime_seconds_average",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}